# Generated by Django 5.1 on 2024-09-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigser', '0002_product_new_product_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigser',
            name='only_logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип только'),
        ),
    ]
