# Generated by Django 5.1 on 2024-09-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigser', '0003_alter_bigser_only_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigser',
            name='logo_black',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип черный'),
        ),
        migrations.AlterField(
            model_name='bigser',
            name='logo_white',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип белый'),
        ),
    ]
