# Generated by Django 5.1 on 2024-09-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigser', '0004_alter_bigser_logo_black_alter_bigser_logo_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigser',
            name='menu_item_contacts_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='меню Контакты'),
        ),
        migrations.AddField(
            model_name='bigser',
            name='menu_item_contacts_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='меню Контакты'),
        ),
        migrations.AddField(
            model_name='bigser',
            name='menu_item_contacts_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='меню Контакты'),
        ),
    ]
