# Generated by Django 5.1 on 2024-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigser', '0005_bigser_menu_item_contacts_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('main', models.BooleanField(default=False, verbose_name='Главная')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Facebook',
                'verbose_name_plural': 'Facebook',
            },
        ),
        migrations.CreateModel(
            name='WhatsappLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('main', models.BooleanField(default=False, verbose_name='Главная')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Whatsapp',
                'verbose_name_plural': 'Whatsapp',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
        migrations.AddField(
            model_name='emails',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
        migrations.AddField(
            model_name='phones',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
