# Generated by Django 5.1 on 2024-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigser', '0006_facebooklinks_whatsapplinks_address_main_emails_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
