# Generated by Django 5.1 on 2024-09-02 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigser', '0008_bigser_popup_text_bigser_popup_text_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigser',
            old_name='popup_title',
            new_name='popup_button',
        ),
        migrations.RenameField(
            model_name='bigser',
            old_name='popup_title_en',
            new_name='popup_button_en',
        ),
        migrations.RenameField(
            model_name='bigser',
            old_name='popup_title_ky',
            new_name='popup_button_ky',
        ),
        migrations.RenameField(
            model_name='bigser',
            old_name='popup_title_ru',
            new_name='popup_button_ru',
        ),
    ]
