# Generated by Django 5.1 on 2024-09-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigser', '0009_rename_popup_title_bigser_popup_button_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramlinks',
            options={'verbose_name': 'Instagram', 'verbose_name_plural': 'Instagram'},
        ),
        migrations.AlterField(
            model_name='bigser',
            name='popup_button',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='попап Кнопка'),
        ),
        migrations.AlterField(
            model_name='bigser',
            name='popup_button_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='попап Кнопка'),
        ),
        migrations.AlterField(
            model_name='bigser',
            name='popup_button_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='попап Кнопка'),
        ),
        migrations.AlterField(
            model_name='bigser',
            name='popup_button_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='попап Кнопка'),
        ),
    ]
