# Generated by Django 5.1 on 2024-09-02 12:50

from django.db import migrations
from django.contrib.auth.models import User


def create_superuser(apps, schema_editor):
    User.objects.create_superuser('tatadmin', 'admin@example.com', 'password')


class Migration(migrations.Migration):

    dependencies = [
        ('bigser', '0010_alter_instagramlinks_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
