version: "3.10"

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    ports:
    - "8030:8030"
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8030"

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24